export default {
    ic_Back: require('../assets/Images/arrowBack.png'),
    ic_Group: require('../assets/Images/Group.jpg'),
    ic_Delete: require('../assets/Images/delete.png'),
    ic_Edit: require('../assets/Images/edit.png'),
    ic_Notify: require('../assets/Images/notification.png'),
    ic_Hair : require('../assets/Images/HairColor.jpeg'),
    ic_LidGirl: require('../assets/Images/LidGir.jpeg'),
    ic_Eyes: require('../assets/Images/Eyes.jpeg'),
    ic_Engine: require('../assets/Images/EngnRpr.jpeg'),
    ic_Msg: require('../assets/Images/Massage.jpeg'),
    ic_BlueNail: require('../assets/Images/BlueNails.jpeg'),
    ic_BlackNail: require('../assets/Images/BlackNails.jpeg'),
    ic_Mesg: require('../assets/Images/message.png'),
    ic_Home: require('../assets/Images/home.png'),
    ic_Profile: require('../assets/Images/profile.png'),
    ic_Notes: require('../assets/Images/notes.png'),
}