export default {
    DATE_25_Jan_2PM: "25 jan - 2:00PM",
    DATE_26_JAn_10AM: "26 jan - 10:00AM",
    HAIR_COLR_CUT: "Hair Color, Hair Cut",
    FACE_MASAG: "Face Massage",
    LARSN_PRK879: "879 Larson Parkways",
    COMPLET: 'Completed',
    REJECT: "Rejected",
    PH_7: "Phase 7, Mohali",
    HAR_COLR_SP: "Hair Color, Hair Spa",
    NL_PNT: "Nail Paint",
    FACIL: "Facial",
    DETN_MNCR: "Detan Manicure",
    NL_ART: "Nail Art",
    HAR_CLR: "Hair Color",
    CHANGE_PRFIL_PIC: "Change Profile Picture",
    FST_NM:"First Name",
    LST_NM: "Last Name",
    DOB: "Date of Birth",
    PHONE_NUM: "Phone Number",
    EMIL:"Email",
    CNTRY: "Country",
    P_ZP_CODE: "Postal/Zip Code",
    LID_VILNSKY: "Lidmila, Vilensky",
    CORDL_DURD: "Corabelle Durrad",
    ZNG_WN: "Zeng Wen",
    OGSWR_KTSM: "Ogasawara Katsumi",
    EDN_SHRMN: "Edna Sherman",
    GRTRD_MCRMCK: "Gertrude McCordmick",
    DOLR_120: "$120",
    DOLR_65: "$65",
    CAR_ENGN_RPR: "Car Engine Repair",
    ON_WAY: "On the Way",
    PRCE_DLR_120: "Price: $120.00",
    PRCE_DLR_80: "Price: $80.00",
    PRCE_DLR_50: "Price: 50.00",
}